### ISSUE TITLE
site_urls undefined

### ISSUE THREAD

**Issue by YukiteruPlease** [bibanon/BASC-py4chan#8]
Attempting to run even the example code provided gives an error with site_urls not being defined, despite not even using an alternate URL.

**Comment by DanielOaks** [comment]
Looking into it. #6 was never actually merged, looks like that was probably an oversight. I've merged that in and that hopefully fixes the issue, will do some testing to confirm (and confirm it works with BASC-archiver, if it all works will push the new version to PyPi). Sorry!

**Comment by DanielOaks** [comment]
Alright, that's pushed to PyPi, the example and BASC-Archiver both seem to work OK with the new code. Thanks very much for the report!

**Comment by antonizoon** [comment]
Thanks for checking this out. I didn't merge in #6 because it was such a massive overhaul of py4chan, and I needed to get your input on it.

On that topic, the overhaul was meant to make it possible for py4chan to be extended to work with other 4chan API compatible systems, such as 8ch and 420chan's API. How about we look into that?

**Comment by DanielOaks** [comment]
Fair enough, looks good to me.

I'm busy for the next week or two, but I'll have a look and start
experimenting with it when I'm not too busy, seeing how to lay the system
out. We've got a similar setup in BASC-Archiver being able to multiplex
different imageboards, so I'll see how applicable that sort of structure
could be good here (ie #7)

Will let you know!
